src/app/main/routes.py
from flask import Blueprint, render_template, redirect, url_for, json, current_app, session, g
from werkzeug.exceptions import HTTPException
from app.db.models import *

main = Blueprint("main", __name__)


# Exception handling
@main.app_errorhandler(HTTPException)
def handle_http_exception(e):
    try:
        return render_template(f"errors/{e.code}.html"), e.code
    except:
        response = e.get_response()
        response.data = json.dumps(
            {
                "code": e.code,
                "name": e.name,
                "description": e.description,
            }
        )
        response.content_type = "mainlication/json"
        return response


# Home page
@main.route("/")
def home():
    return redirect(url_for("user.login"))


# For debug purposes
@main.route("/view")
def view():
    return render_template(
        "view.html",
        couriers=Courier.query.all(),
        trips=Trip.query.all(),
        db_info=current_app.config.get("SQLALCHEMY_DATABASE_URI"),
    )

src/app/user/routes.py
from flask import (
    Blueprint,
    session,
    request,
    flash,
    redirect,
    url_for,
    render_template,
)
from flask.globals import current_app
from app.user.utils import *
from app.db.models import *

user = Blueprint("user", __name__, url_prefix="/user")


@user.before_request
def load_user():
    g.user = Courier.query.filter_by(id=session.get("id")).first()


# Login page
@user.route("/login", methods=["POST", "GET"])
def login():

    if g.user:
        flash("Already logged in!")
        return redirect(url_for("user.dashboard"))

    if request.method == "POST":
        email = request.form["email"].strip()

        insert_into_db(Courier(email), db)

        g.user = Courier.query.filter_by(email=email).first()

        session.permanent = True
        session["status"] = "inactive"
        session["id"] = g.user.id

        if g.user.current_trip_id:
            flash("You have a trip in progress!")
            session["status"] = "active"
            return redirect(
                url_for("user.trip_dashboard", tripID=g.user.current_trip_id)
            )

        flash("Login successful!")
        return redirect(url_for("user.inactive"))

    return render_template("user/login.html")


# Endpoint for user settings page
@user.route("/settings", methods=["POST", "GET"])
def settings():

    if not g.user:
        flash("Invalid user or session expired!")
        return redirect(url_for("user.logout"))

    if g.user.current_trip_id:
        flash("You have a trip in progress!")
        return redirect(url_for("user.dashboard", tripID=g.user.current_trip_id))

    if request.method == "POST":

        tags = request.form.getlist("tag-checkbox")
        g.user.name = request.form["name"].strip()
        g.user.max_weight = request.form["weight"]
        g.user.max_width = request.form["width"]
        g.user.max_height = request.form["height"]
        g.user.max_length = request.form["length"]
        g.user.tags = ",".join(tags) if tags else ""
        g.user.is_validated = True
        db.session.commit()

        flash("Information was saved!")
        return redirect(url_for("user.dashboard"))

    return render_template(
        "user/settings.html",
        name=g.user.name,
        max_weight=g.user.max_weight,
        max_width=g.user.max_width,
        max_height=g.user.max_height,
        max_length=g.user.max_length,
        tags=[x for x in g.user.tags.split(",") if x],
        available_tags=AVAILABLE_TAGS,
    )


# Endpoint for user logout
@user.route("/logout")
def logout():

    if g.user:
        name = g.user.name

    clear_session(session)
    flash(f"You have been logged out, {name}!", "info")
    
    return redirect(url_for("user.login"))


# User is redirected here upon going inactive
@user.route("/inactive", methods=["GET", "POST"])
def inactive():

    if not g.user:
        flash("Invalid user or session expired!")
        return redirect(url_for("user.login"))

    if not g.user.is_validated:
        flash("You need to complete your profile first!")
        return redirect(url_for("user.settings"))

    if g.user.current_trip_id:
        flash("You have a trip in progress!")
        return redirect(url_for("user.trip_dashboard", tripID=g.user.current_trip_id))

    if request.method == "POST":
        if request.form.get("submit") == "active":
            session["status"] = "active"
            return redirect(url_for("user.dashboard"))

    session["status"] = "inactive"

    return render_template("user/inactive.html", name=g.user.name)


# Endpoint for the user dashboard
@user.route("/dashboard", methods=["POST", "GET"])
def dashboard():

    if not g.user:
        flash("Invalid user or session expired!")
        return redirect(url_for("user.login"))

    if session["status"] == "inactive":
        flash("You are currently inactive!")
        return redirect(url_for("user.inactive"))

    if not g.user.is_validated:
        flash("You need to complete your profile first!")
        return redirect(url_for("user.settings"))

    if g.user.current_trip_id:
        flash("You have a trip in progress!")

        return redirect(url_for("user.trip_dashboard", tripID=g.user.current_trip_id))

    if request.method == "POST":
        orderID = request.args.get("orderID")
        distance = request.args.get("distance")

        if not check_order_availability(orderID):
            flash("Order was already taken, completed or cancelled!")
            return redirect(url_for("user.dashboard"))

        init_trip(g.user, orderID, distance)

        return redirect(
            url_for(
                "user.trip_dashboard", tripID=g.user.current_trip_id, status="ASSIGNED"
            )
        )

    page = int(request.args.get("page")) if request.args.get("page") else 1

    # Request orders from order management
    orders = get_orders(
        maxWeight=g.user.max_weight,
        maxHeight=g.user.max_height,
        maxWidth=g.user.max_width,
        maxLength=g.user.max_length,
        tags=g.user.tags.split(","),
        page=page - 1,
    )

    data = orders.get("data") if orders.get("data") else []
    pagination = orders.get("pagination")

    for order in data:
        order["distance"] = round(
            haversine_distance(
                order["from"]["latitude"],
                order["from"]["longitude"],
                order["to"]["latitude"],
                order["to"]["longitude"],
            ),
            2,
        )

    if not orders:
        flash("There was a problem!")

    return render_template(
        "user/dashboard.html", name=g.user.name, data=data, pagination=pagination
    )


# Endpoint for order status change
@user.route("/dashboard/<tripID>", methods=["GET", "POST"])
def trip_dashboard(tripID):

    trip = Trip.query.filter_by(id=tripID).first_or_404()

    if not g.user:
        flash("Invalid user or session expired!")
        return redirect(url_for("user.login"))

    if not g.user.is_validated:
        flash("You need to complete your profile first!")
        return redirect(url_for("user.settings"))

    if g.user.current_trip_id and tripID != g.user.current_trip_id:
        flash("You have a trip in progress!")
        return redirect(url_for("user.trip_dashboard", tripID=g.user.current_trip_id))

    order = get_order_by_id(trip.order_id)

    # Get requested trip status
    if request.method == "POST":
        status = request.args.get("status")

        if (trip.status == "ASSIGNED" and status in ["CANCELLED", "PICKED_UP"]) or (
            trip.status == "PICKED_UP" and status == "COMPLETED"
        ):
            if status:
                current_app.logger.debug(status)
                change_order_status(trip.order_id, status)
            status = change_trip_status(status, g.user, trip)
        else:
            flash("Invalid operation!")

    return render_template("user/order.html", order=order, trip=trip)


# Endpoint for trips history
@user.route("/history")
def history():

    if not g.user:
        flash("Invalid user or session expired!")
        return redirect(url_for("user.login"))

    if not g.user.is_validated:
        flash("You need to complete your profile first!")
        return redirect(url_for("user.settings"))

    if g.user.current_trip_id:
        flash("You have a trip in progress!")
        return redirect(url_for("user.trip_dashboard", tripID=g.user.current_trip_id))

    limit = 5
    older_than = request.args.get("older_than")
    newer_than = request.args.get("newer_than")

    # Get paginated history
    history = paginate(g.user.id, older_than, newer_than, limit + 1)
    # Remove first or last element based on action
    history = (
        (history[1:] if newer_than else history[:-1])
        if len(history) > limit
        else history
    )

    # Check buttons availability
    older = (older_than and len(history) > limit) or (
        history
        and len(paginate(g.user.id, history[-1].get("sorter"), None, limit + 1)) > 0
    )
    newer = (newer_than and len(history) > limit) or (
        history
        and len(paginate(g.user.id, None, history[0].get("sorter"), limit + 1)) > 0
    )

    return render_template("user/history.html", items=history, older=older, newer=newer)


# Endpoint for courier stats
@user.route("/statistics")
def statistics():

    if not g.user:
        flash("Invalid user or session expired!")
        return redirect(url_for("user.login"))

    if not g.user.is_validated:
        flash("You need to complete your profile first!")
        return redirect(url_for("user.settings"))

    return render_template(
        "user/statistics.html",
        completed_trips=get_count_completed_trips(g.user.id),
        cancelled_trips=get_count_cancelled_trips(g.user.id),
        total_distance=get_total_distance(g.user.id),
        earnings=get_earnings(g.user.id),
    )

src/app/templates/base.html
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    {% block style %}{% endblock %}

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">
    <link href="{{ url_for('static', filename='css/style.css') }}" rel="stylesheet">

    <title>{% block title %}{% endblock %}</title>
    {% block links %}{% endblock %}
</head>

<body>

    {% block navbar %}{% endblock %}

    <div class="d-flex justify-content-center align-items-center alert-container" data-mdb-sticky-direction="both">
        {% with messages=get_flashed_messages() %}
        {% if messages %}
        <div class="overlay">
            <div class="toast alert alert-primary alert-dismissible fade show" role="alert" aria-live="assertive"
                aria-atomic="true" style="position: relative; z-index:1;">
                {{messages[-1]}}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
                </button>
            </div>
        </div>
        {% endif %}
        {% endwith %}
    </div>

    {% block content %}{% endblock %}

    <script src="https://code.jquery.com/jquery-3.6.0.min.js"
        integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous">
    </script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous">
    </script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-/bQdsTh/da6pkI1MST/rWKFNjaCP5gBSY4sEBT38Q/9RBh9AH40zEOg7Hlq2THRZ" crossorigin="anonymous">
    </script>

    {% block scripts %}{% endblock %}
</body>

</html>

src/app/templates/index.html
{% extends "base.html" %}

{% block title %} Login Page {% endblock %}

{%block content%}
<h1>Welcome to Uber Deliveries!</h1>
<form method="POST">
    <input type="submit" name="login_button" value="Login" />
</form>
{%endblock%}

src/app/templates/navbar.html
{% extends "base.html" %}

{% block navbar %}
<style>
    .nav{
        position: -webkit-sticky;
        position: sticky;
        top: 0;
        z-index: 99;
    }
</style>

<nav class="nav navbar navbar-expand-lg navbar-dark bg-dark">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
        aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
            <!--<li class="nav-item">
                <a class="nav-link" href="{{ url_for('main.view') }}" target="_blank">View</a>
            </li>-->
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('user.dashboard') }}">Dashboard</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('user.settings') }}">Settings</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('user.history') }}">History</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('user.statistics') }}">Statistics</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('user.logout') }}">Log out</a>
            </li>
        </ul>
    </div>
</nav>
{% endblock %}

src/app/templates/view.html
{% extends "base.html" %}

{% block title%}View All Users{% endblock %}

{% block content %}

<h1>COURIERS:</h1>
{% for item in couriers %}
<p>{{item.dict()}}</p>
{% endfor %}

<h1>TRIPS:</h1>

{% for item in trips %}
<p>{{item.dict()}}</p>
{% endfor %}

<h1>{{db_info}}</h1>

{% endblock %}